# Generated by Django 4.1.3 on 2022-12-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdropmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='airdropmodel',
            name='frequency',
            field=models.CharField(choices=[('select', 'Select'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('once', 'Once')], default='Select', max_length=10),
        ),
    ]
